apiVersion: apps/v1
kind: Deployment
metadata:
  name: dagdu-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dagdu
  template:
    metadata:
      labels:
        app: dagdu
    spec:
      containers:
        - name: dagdu-container
          image: saurabh1307/dagdu-app:v2
          ports:
            - containerPort: 80
          resources:
           requests:
             cpu: "100m"
             memory: "100Mi"
           limits:
             cpu: "200m"
             memory: "200Mi"
